server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    request-context-attribute: request
  resources:
    static-locations: classpath:/static/,file:/var/www/upload/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    # 邮件服务地址
    host: smtp.exmail.qq.com
    # 端口,可不写默认
    port: 465
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: xxxxx@xxxx.com
    # 授权码
    password: xxxx
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
user:
  avatar-dir: /var/www/upload/
#mybatis配置
mybatis:
  #mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fly.frontend.entity
  #允许驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# set log level
#logging:
#    level:
#      root: DEBUG