language: java
jdk: openjdk8

services:
  - docker

install:
  - echo ${DOCKER_HOST}

script:
  - mvn clean && mvn package -pl fly-frontend -am -amd -DskipTests=true
  - docker build -t fly/frontend .


after_success: skip
