language: java
jdk: openjdk8

services:
  - docker

# build docker image
install:
  - mvn clean && mvn package -pl fly-frontend -am -amd -DskipTests=true
  - docker build -t peng49/fly-frontend:v0.1 .
  - docker images

script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker push peng49/fly-frontend:v0.1

after_success: skip
