language: java
jdk: openjdk8

services:
  - docker

install: skip

script:
  - mvn clean && mvn package -pl fly-frontend -am -amd -DskipTests=true
  - docker build -t ${DOCKER_HOST}/fly/frontend .
  - docker push ${DOCKER_HOST}/fly/frontend

after_success: skip
