language: java
jdk: openjdk8

services:
  - docker

# 跳过空模块的自动构建
install: skip

script:
  - mvn clean && mvn package -pl fly-frontend -am -amd -DskipTests=true
  - docker pull openjdk:8u265-jre
  - docker build -t ${DOCKER_HOST}/fly/frontend .
  - docker push ${DOCKER_HOST}/fly/frontend

after_success: skip
