spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fly?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root@123
  jpa:
#    database: MySQL
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

