server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    #    view:
    #      prefix: /WEB-INF/templates/
    #      suffix: .jsp
    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    request-context-attribute: request
  resources:
    static-locations: classpath:/static/,file:E:/vagrant-java/fly-avatar/
  # datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fly?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root@123
  mail:
    # 邮件服务地址
    host: smtp.exmail.qq.com
    # 端口,可不写默认
    port: 465
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: yypeng@sfcservice.com
    # 授权码，就是我们刚才准备工作获取的代码
    password: Py921219
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
user:
  avatar-dir: E:/vagrant-java/fly-avatar/
#mybatis配置
mybatis:
  #mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fly.frontend.entity
  #允许驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
oauth:
  gitee:
    client-id: xxx
    client-secret: xxxx
    redirect-uri: http://localhost:8001/oauth/gitee/callback
# set log level
#logging:
#    level:
#      root: DEBUG