server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  resources:
    static-locations: classpath:/static/,file:E:/vagrant-java/fly-avatar/
  # datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fly?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root@123
user:
  avatar-dir: E:/vagrant-java/fly-avatar/
#mybatis配置
mybatis:
  #mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fly.frontend.entity
  #允许驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#pagehelper 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql