server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .jsp
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/,file:F:/develop/vagrant-java/fly-avatar/
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fly?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root@123
user:
  avatar-dir: F:/develop/vagrant-java/fly-avatar/
#mybatis配置
mybatis:
  #mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fly.frontend.entity
  #允许驼峰命名
  configuration:
    map-underscore-to-camel-case: true
