name: Docker Image CI

on:
  push:
    tags: [ "v*.*.*" ]
#    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch Tags
        run: |
          git fetch --all --tags
          echo "tag version: " $(git describe --tags "$(git rev-list --tags --max-count=1)")

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag peng49/fly:$(git describe --tags "$(git rev-list --tags --max-count=1)")

      - name: Deploy Image
        env:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker tag peng49/fly:$(git describe --tags "$(git rev-list --tags --max-count=1)") peng49/fly:latest
          echo "${password}" | docker login -u "${username}" --password-stdin
          docker push peng49/fly:latest
          docker push peng49/fly:$(git describe --tags "$(git rev-list --tags --max-count=1)")
